"""empty message

Revision ID: 4e24d99d5ac4
Revises: 74f1c885fb48
Create Date: 2025-07-07 21:02:49.670070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e24d99d5ac4'
down_revision = '74f1c885fb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['temp_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('temp_id')

    # ### end Alembic commands ###
