"""empty message

Revision ID: a7d3c10a82ad
Revises: 
Create Date: 2025-07-08 15:56:22.141360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d3c10a82ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country')
    )
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_city_country_id'), ['country_id'], unique=False)

    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address1', sa.String(length=128), nullable=False),
    sa.Column('address2', sa.String(length=128), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('zipcode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_city_id'), ['city_id'], unique=False)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('account_type', sa.Enum('REGULAR', 'ADMIN', 'SUPERUSER', name='accounttype'), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('temp_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('upvotes_cnt', sa.Integer(), nullable=False),
    sa.Column('dnvotes_cnt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('temp_id')
    )
    op.create_table('user_audit',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username_old', sa.String(length=80), nullable=False),
    sa.Column('username_new', sa.String(length=80), nullable=False),
    sa.Column('password_old', sa.String(length=255), nullable=False),
    sa.Column('password_new', sa.String(length=255), nullable=False),
    sa.Column('account_type_old', sa.Enum('SuperUser', name='accounttype'), nullable=False),
    sa.Column('account_type_new', sa.Enum('SuperUser', name='accounttype'), nullable=False),
    sa.Column('created_at_old', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at_new', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at_old', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at_new', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='action'), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('audit_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_user'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('user_detail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=True),
    sa.Column('l_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('temp_id', sa.String(length=36), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('upvotes_cnt', sa.Integer(), nullable=False),
    sa.Column('dnvotes_cnt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id'),
    sa.UniqueConstraint('temp_id')
    )
    op.create_table('post_votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_direction', sa.Enum('UP', 'DOWN', 'NONE', name='votedirection'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('comment_votes',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_direction', sa.Enum('UP', 'DOWN', 'NONE', name='votedirection'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_votes')
    op.drop_table('post_votes')
    op.drop_table('comment')
    op.drop_table('user_detail')
    op.drop_table('user_audit')
    op.drop_table('post')
    op.drop_table('notification')
    op.drop_table('message')
    op.drop_table('user')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_city_id'))

    op.drop_table('address')
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_country_id'))

    op.drop_table('city')
    op.drop_table('country')
    op.drop_table('chat')
    # ### end Alembic commands ###
