swagger: '2.0'
info:
  title: 'Group 5 - Mediline REST API'
  description: 'For CS490. API documentation'
  version: '0.1'
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: >-
      JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"
security:
  - Bearer: []
definitions:
  Appointment:
    type: object
    required:
    - doctor_id
    - patient_id
    properties:
      appointment_id:
        type: integer
      doctor_id:
        type: integer
      patient_id:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
      doctor:
        $ref: '#/definitions/Doctor'
      patient:
        $ref: '#/definitions/Patient'
      appointment_detail:
        $ref: '#/definitions/AppointmentDetail'
      chat:
        $ref: '#/definitions/Chat'
  AppointmentDetail:
    type: object
    required:
    - appointment_details_id
    - treatment
    - start_date
    - status
    properties:
      appointment_details_id:
        type: integer
      treatment:
        type: string
      start_date:
        type: string
        format: date-time
      end_date:
        type: string
        format: date-time
      status:
        type: string
        enum: [pending, confirmed, cancelled, completed]
  Address:
    type: object
    required:
    - address1
    - city_id
    - state
    - zipcode
    properties:
      address_id:
        type: integer
      address1:
        type: string
      address2:
        type: string
      city_id:
        type: integer
      state:
        type: string
      zipcode:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      city:
        $ref: '#/definitions/City'
  City:
    type: object
    required:
    - city
    - country_id
    properties:
      city_id:
        type: integer
      city:
        type: string
      country_id:
        type: integer
      addresses:
        type: array
        items:
          $ref: '#/definitions/Address'
      country:
        $ref: '#/definitions/Country'
  Country:
    type: object
    required:
    - country
    properties:
      country_id:
        type: integer
      country:
        type: string
      cities:
        type: array
        items:
          $ref: '#/definitions/City'
  User:
    type: object
    required:
    - username
    - password
    - account_type
    - email
    - phone
    properties:
      user_id:
        type: integer
      username:
        type: string
      password:
        type: string
        format: password
      address_id:
        type: integer
      account_type:
        type: string
        enum: [doctor, patient, pharmacy, super_user]
      email:
        type: string
      phone:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      address:
        $ref: '#/definitions/Address'
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
      patient:
        $ref: '#/definitions/Patient'
      doctor:
        $ref: '#/definitions/Doctor'
      pharmacy:
        $ref: '#/definitions/Pharmacy'
      posts:
        type: array
        items:
          $ref: '#/definitions/Post'
      comments:
        type: array
        items:
          $ref: '#/definitions/Comment'
  Doctor:
    allOf:
    - $ref: '#/definitions/User'
    - type: object
      required:
      - first_name
      - last_name
      - specialization
      - fee
      - dob
      - license_id
      properties:
        first_name:
          type: string
        last_name:
          type: string
        specialization:
          type: string
        bio:
          type: string
        fee:
          type: number
          format: float
        profile_picture:
          type: string
          format: byte
        dob:
          type: string
          format: date
        license_id:
          type: string
        patients:
          type: array
          items:
            $ref: '#/definitions/Patient'
        user:
          $ref: '#/definitions/User'
        appointments:
          type: array
          items:
            $ref: '#/definitions/Appointment'
        patient_exercises:
          type: array
          items:
            $ref: '#/definitions/PatientExercise'
        invoices:
          type: array
          items:
            $ref: '#/definitions/Invoice'
        prescriptions:
          type: array
          items:
            $ref: '#/definitions/Prescription'
        patient_reports:
          type: array
          items:
            $ref: '#/definitions/PatientReport'
        rating_surveys:
          type: array
          items:
            $ref: '#/definitions/RatingSurvey'
  Patient:
    allOf:
    - $ref: '#/definitions/User'
    - type: object
      required:
      - first_name
      - last_name
      - dob
      properties:
        first_name:
          type: string
        last_name:
          type: string
        dob:
          type: string
          format: date
        doctor_id:
          type: integer
        pharmacy_id:
          type: integer
        doctor:
          $ref: '#/definitions/Doctor'
        pharmacy:
          $ref: '#/definitions/Pharmacy'
        user:
          $ref: '#/definitions/User'
        appointments:
          type: array
          items:
            $ref: '#/definitions/Appointment'
        patient_exercises:
          type: array
          items:
            $ref: '#/definitions/PatientExercise'
        invoices:
          type: array
          items:
            $ref: '#/definitions/Invoice'
        prescriptions:
          type: array
          items:
            $ref: '#/definitions/Prescription'
        patient_reports:
          type: array
          items:
            $ref: '#/definitions/PatientReport'
        rating_surveys:
          type: array
          items:
            $ref: '#/definitions/RatingSurvey'
  Pharmacy:
    allOf:
    - $ref: '#/definitions/User'
    - type: object
      required:
      - pharmacy_name
      - hours
      properties:
        pharmacy_name:
          type: string
        hours:
          type: string
        patients:
          type: array
          items:
            $ref: '#/definitions/Patient'
        user:
          $ref: '#/definitions/User'
  Message:
    type: object
    required:
    - chat_id
    - user_id
    - message_content
    properties:
      message_id:
        type: integer
      chat_id:
        type: integer
      user_id:
        type: integer
      message_content:
        type: string
      time:
        type: string
        format: date-time
      chat:
        $ref: '#/definitions/Chat'
      user:
        $ref: '#/definitions/User'
  Chat:
    type: object
    required:
    - appointment_id
    properties:
      chat_id:
        type: integer
      appointment_id:
        type: integer
      start_date:
        type: string
        format: date-time
      end_date:
        type: string
        format: date-time
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
      appointment:
        $ref: '#/definitions/Appointment'
  ExerciseBank:
    type: object
    required:
    - type_of_exercise
    - description
    properties:
      exercise_id:
        type: integer
      type_of_exercise:
        type: string
      description:
        type: string
      patient_exercises:
        type: array
        items:
          $ref: '#/definitions/PatientExercise'
  PatientExercise:
    type: object
    required:
    - exercise_id
    - patient_id
    - doctor_id
    - reps
    - status
    - created_at
    properties:
      exercise_id: 
        type: integer
      patient_id: 
        type: integer
      doctor_id: 
        type: integer
      reps: 
        type: string
      status: 
        type: string
        enum:
        - in_progress
        - completed
      created_at: 
        type: string
        format: date-time
      exercise:
        $ref: '#/definitions/ExerciseBank'
      patient:
        $ref: '#/definitions/Patient'
      doctor:
        $ref: '#/definitions/Doctor'
  Invoice:
    type: object
    required:
    - patient_id
    - doctor_id
    - status
    properties:
      invoice_id:
        type: integer
      patient_id:
        type: integer
      doctor_id:
        type: integer
      status:
        type: string
        enum:
        - paid
        - pending
      pay_date:
        type: string
        format: date
      created_at:
        type: string
        format: date-time
      patient:
        $ref: '#/definitions/Patient'
      doctor:
        $ref: '#/definitions/Doctor'
  Prescription:
    type: object
    required:
    - patient_id
    - doctor_id
    - amount
    - status
    properties:
      prescription_id:
        type: integer
      patient_id:
        type: integer
      doctor_id:
        type: integer
      amount:
        type: number
        format: float
      status:
        type: string
        enum:
        - paid
        - unpaid
      created_at:
        type: string
        format: date-time
      prescription_medications:
        type: array
        items:
          $ref: '#/definitions/PrescriptionMedication'
  PrescriptionMedication:
    type: object
    required:
    - prescription_id
    - medication_id
    - dosage
    - medical_instructions
    properties:
      prescription_medication_id:
        type: integer
      prescription_id:
        type: integer
      medication_id:
        type: integer
      dosage:
        type: string
      medical_instructions:
        type: string
      prescription:
        $ref: '#/definitions/Prescription'
      medication:
        $ref: '#/definitions/Medication'
  Medication:
    type: object
    required:
    - name
    - description
    properties:
      medication_id:
        type: integer
      name:
        type: string
      description:
        type: string
      prescription_medications:
        type: array
        items:
          $ref: '#/definitions/PrescriptionMedication'
  Report:
    type: object
    required:
    - type
    properties:
      report_id:
        type: integer
      type:
        type: string
        enum:
          - daily
          - weekly
          - monthly
      created_at:
        type: string
        format: date-time
      patient_reports:
        type: array
        items:
          $ref: '#/definitions/PatientReport'
  PatientReport:
    type: object
    required:
    - report_id
    - patient_id
    - doctor_id
    properties:
      patient_report_id:
        type: integer
      report_id:
        type: integer
      patient_id:
        type: integer
      doctor_id:
        type: integer
      height:
        type: number
        format: float
      weight:
        type: number
        format: float
      calories_intake:
        type: integer
      hours_of_exercise:
        type: integer
      hours_of_sleep:
        type: integer
      created_at:
        type: string
        format: date-time
      report:
        $ref: '#/definitions/Report'
      patient:
        $ref: '#/definitions/Patient'
      doctor:
        $ref: '#/definitions/Doctor'
  Post:
    type: object
    required:
    - user_id
    - title
    properties:
      post_id:
        type: integer
      user_id:
        type: integer
      title:
        type: string
      content:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      user:
        $ref: '#/definitions/User'
      comments:
        type: array
        items:
          $ref: '#/definitions/Comment'
  Comment:
    type: object
    required:
    - post_id
    - user_id
    - content
    properties:
      comment_id:
        type: integer
      post_id:
        type: integer
      user_id:
        type: integer
      content:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      post:
        $ref: '#/definitions/Post'
      user:
        $ref: '#/definitions/User'
  RatingSurvey:
    type: object
    required:
    - survey_id
    - patient_id
    - doctor_id
    - stars
    properties:
      survey_id:
        type: integer
      patient_id:
        type: integer
      doctor_id:
        type: integer
      comment:
        type: string
      stars:
        type: integer
      patient:
        $ref: '#/definitions/Patient'
      doctor:
        $ref: '#/definitions/Doctor'